name: Unit Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test
